### ISSUE TITLE
UI changes for Telegram button (Frontend)

### ISSUE THREAD

**Issue by bnonni** [ATLBitLab/abbot#61]
In UI Telegram button should look like Nostr 
When the user clicks telegram button the UI will show 2 buttons:

- DM Abbot
- Telegram group

When the user clicks on DM Abbot it will go straight to Telegram message 
When the user clicks on Telegram group UI will show a Text box for the user to copy their telegram groupID or link (TBD)

**Comment by saucy-tech** [comment]
**Issue Update for #61: Adding Telegram Buttons**

**Work Completed:**
- Initiated `lolv2-brandon-61-frontend-telegram` branch for focused development.
- Developed interactive UI components for Telegram and Nostr button functionalities.
- Enhanced the main component to manage platform and channel button interactions effectively.
- Implemented features for resetting to the initial state, handling form submissions, and displaying loading indicators.
- Conducted code refactoring for improved readability and efficiency, removing unnecessary dependencies.

**Work In Progress:**
- Investigating Telegram group ID/link integration methods as part of Issue #58 research.
- Planning to restore the button color change functionality upon selection, which was inadvertently removed in recent updates.

**Next Steps:**
- Refine button text based on results from Issue #58.
- Finalize the input method for Telegram group ID/link, ensuring user-friendly interaction.
- Introduce and test a new variable specifically for the Telegram group ID/link.
- Conduct comprehensive testing of all new and modified UI elements to ensure reliability and user satisfaction.

**Other Enhancements:**
- Implemented a new button for Abbot help/onboarding along with a corresponding boilerplate page.
- Made minor updates to the team page.
- Created new branch name to reflect updated issue number.

**Comment by bnonni** [comment]
@saucy-tech can you submit a PR referencing this issue between branched `lolv2` and `lolv2-brandon-61-frontend-telegram` assign yourself as the assignee and me as the reviewer. Thanks!
